sudo: required

language: python

services:
  - docker

before_install:
  - docker run -d  -e CORENLP_ARCHIVE_VERSION=2018-01-31 -p 9000:9000 konradstrack/corenlp

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - python3 setup.py install

script:
  - python3 setup.py test